name: battle-buds
services:
  app:
    build:
      dockerfile: app.Dockerfile
    ports:
      # jMonkeyEngine requires both TCP and UDP to be open, even if only TCP is used
      - "34000:34000/tcp"
      - "34000:34000/udp"
    restart: always